from pathlib import Path


supported = {
    "windows": ["amd64", "arm64"],
    "darwin": ["amd64", "arm64"],
    "linux": ["amd64", "arm64", "mips64", "mips64le", "ppc64", "ppc64le"],
}


def gen():
    for key, values in supported.items():
        yield "({} && ({}))".format(key, " || ".join(values))


with Path(__file__).joinpath("../platform.generated.go").open("w", encoding="utf8") as f:
    print('// Code generated by "generate.py"; DO NOT EDIT.', file=f)
    print("//go:build " + " || ".join(gen()), file=f)
    print("", file=f)
    print("package platform", file=f)
    print("", file=f)
    print("const platform_supported = 0", file=f)
