// Code generated by "generate_support_platform.py"; DO NOT EDIT.
//go:build (windows && (amd64 || arm64)) || (darwin && (amd64 || arm64)) || (linux && (amd64 || arm64 || mips64 || mips64le || ppc64 || ppc64le))

package platform

const platform_supported = 0
