// Code generated by "stringer -type=State"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Downloading-0]
	_ = x[Stopped-1]
	_ = x[Seeding-2]
	_ = x[Checking-3]
	_ = x[Moving-3]
	_ = x[Error-4]
}

const _State_name = "DownloadingStoppedSeedingCheckingError"

var _State_index = [...]uint8{0, 11, 18, 25, 33, 38}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
